"""
Scraper trigger and file download endpoints.
"""

from pathlib import Path
from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from pydantic import BaseModel, Field

from backend.services.scraper_service import ScraperService
from config import CONFIG

router = APIRouter(tags=["Scraper"])


class ScrapeRequest(BaseModel):
    """Payload to trigger scraping job."""
    source: str = Field(default="all", description="Target source: 'all', 'books', or 'quotes'")
    max_pages: int | None = Field(default=None, description="Optional page limit per source for testing")


@router.post("/scrape")
def trigger_scrape(payload: ScrapeRequest = ScrapeRequest()):
    """
    Trigger the Python web scraping pipeline.
    Prevents concurrent executions with an in-memory lock.
    """
    result = ScraperService.trigger_scrape(
        source=payload.source,
        max_pages=payload.max_pages,
    )

    if result.get("status") == "running":
        return result

    if result.get("status") == "error":
        raise HTTPException(status_code=500, detail=result.get("message"))

    return result


@router.get("/download/csv")
def download_csv():
    """Download the actual final_dataset.csv generated by the Python pipeline."""
    csv_path = CONFIG.CSV_OUTPUT_PATH
    if not csv_path.exists():
        raise HTTPException(status_code=404, detail="Dataset CSV not found. Please run the scraper first.")
    return FileResponse(
        path=csv_path,
        media_type="text/csv",
        filename="final_dataset.csv",
    )


@router.get("/download/summary")
def download_summary():
    """Download the actual summary_report.json generated by the Python pipeline."""
    json_path = CONFIG.SUMMARY_JSON_PATH
    if not json_path.exists():
        raise HTTPException(status_code=404, detail="Summary JSON not found. Please run the scraper first.")
    return FileResponse(
        path=json_path,
        media_type="application/json",
        filename="summary_report.json",
    )
